# Sample configuration file for training a 3D U-Net on a task of predicting the boundaries in 3D stack of the Arabidopsis
# ovules acquired with the confocal microscope. Training done with a combination of Binary Cross-Entropy and DiceLoss.
# Download train data from: https://osf.io/x9yns/
# Download validation data from: https://osf.io/xp5uf/
# Download test data from: https://osf.io/8jz7e/
model:
  name: HiPaSNet
  # number of input channels to the model
  in_channels: 2
  # number of output channels
  out_channels: 2
  # determines the order of operators in a single layer (crg - Conv3d+ReLU+GroupNorm)
  layer_order: gcr
  # initial number of feature maps
  f_maps: 32
  # number of groups in the groupnorm
  num_groups: 8
  # apply element-wise nn.Sigmoid after the final 1x1x1 convolution, otherwise apply nn.Softmax
  final_sigmoid: true
# loss function to be used during training
loss:
  name: SoftDiceclDice
  #name: DiceLoss
  # a target value that is ignored and does not contribute to the input gradient
  ignore_index: null
  # skip the last channel in the target (i.e. when last channel contains data not relevant for the loss)
  skip_last_target: false
optimizer:
  # initial learning rate
  learning_rate: 0.00002
  # weight decay
  weight_decay: 0.0001
# evaluation metric
eval_metric:
  # use AdaptedRandError metric
  name: DiceCoefficient
  # probability maps threshold
  threshold: 0.5
  # use the last target channel to compute the metric
  use_last_target: true
  # use only the first channel for computing the metric
  use_first_input: true
lr_scheduler:
  name: ReduceLROnPlateau
  # make sure to use the 'min' mode cause lower AdaptedRandError is better
  mode: min
  factor: 0.8
  patience: 30
trainer:
  # model with higher eval score is considered better
  eval_score_higher_is_better: True
  # path to the checkpoint directory
  checkpoint_dir: /data/AV/med_checkpoint
  # path to latest checkpoint; if provided the training will be resumed from that checkpoint
  resume: null
  # path to the best_checkpoint.pytorch; to be used for fine-tuning the model with additional ground truth
  pre_trained: null
  # how many iterations between validations
  validate_after_iters: 1000
  # how many iterations between tensorboard logging
  log_after_iters: 100
  # max number of epochs
  max_num_epochs: 4
  # max number of iterations
  max_num_iterations: 1500000
# Configure training and validation loaders
loaders:
  # number of patches per batch
  batch_size: 2
  # how many subprocesses to use for data loading
  num_workers: 8
  # path to the raw data within the H5
  raw_internal_path: /raw
  # path to the the label data withtin the H5
  label_internal_path: /label
  # configuration of the train loader
  train:
    # path to the training datasets
    file_paths:
      - /data/Train_and_Test/Artery_Vein/whole_av/fold_1

    # SliceBuilder configuration, i.e. how to iterate over the input volume patch-by-patch
    slice_builder:
      name: SliceBuilder
      # train patch size given to the network (adapt to fit in your GPU mem, generally the bigger patch the better)
      patch_shape: [160, 160, 128]
      # train stride between patches
      stride_shape: [43, 37, 29]
#      # minimum volume of the labels in the patch
#      threshold: 0.6
#      # probability of accepting patches which do not fulfil the threshold criterion
#      slack_acceptance: 0.01

    transformer:
      raw:
#        - name: Standardize
#        - name: RandomRotate90
        - name: ElasticDeformation
          spline_order: 3
        - name: GaussianBlur3D
          execution_probability: 0.5
        - name: AdditiveGaussianNoise
          execution_probability: 0.2
        - name: AdditivePoissonNoise
          execution_probability: 0.2
        - name: ToTensor
          expand_dims: false
      label:
#        - name: RandomRotate90
        - name: ElasticDeformation
          spline_order: 0
        - name: ToTensor
          expand_dims: false

  # configuration of the val loader
  val:
    # path to the val datasets
    file_paths:
      - /data/Train_and_Test/Artery_Vein/whole_av/fold_2

    # SliceBuilder configuration, i.e. how to iterate over the input volume patch-by-patch
    slice_builder:
      name: SliceBuilder
      # train patch size given to the network (adapt to fit in your GPU mem, generally the bigger patch the better)
      patch_shape: [192, 192, 128]
      # train stride between patches
      stride_shape: [64, 64, 48]
#      # minimum volume of the labels in the patch
#      threshold: 0.6
#      # probability of accepting patches which do not fulfil the threshold criterion
#      slack_acceptance: 0.01

    # data augmentation
    transformer:
      raw:
        - name: Standardize
        - name: ToTensor
          expand_dims: false
      label:
        - name: ToTensor
          expand_dims: false